name: iOS CSE CI
on:
  pull_request:
    branches: ["main"]
jobs:
  ci:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3

      - name: Pod Lint
        run: |
          pod lib lint
