name: Notification
on:
  pull_request:
    types: [opened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  slack:
    name: Ready For Review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kv109/action-ready-for-review@0.2
      env:
        SLACK_CHANNEL: tech-reviews
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TECH_REVIEWS }}
        PR_APPROVED_FORMAT: |
          :verified: *${{ github.event.repository.name }}* pull request *approved* by { review.user.login }: <{ pull_request.html_url }|{ pull_request.title }>
        PR_READY_FOR_REVIEW_FORMAT: |
          :github: *${{ github.event.repository.name }}* pull request *opened* by { pull_request.user.login }: <{ pull_request.html_url }|{ pull_request.title }>
        PR_REJECTED_FORMAT: |
          :warning: *${{ github.event.repository.name }}* pull request *rejected* by { review.user.login }: <{ pull_request.html_url }|{ pull_request.title }>
        PR_COMMENTED_FORMAT: |
          :paperclip: *${{ github.event.repository.name }}* pull request *commented* by { review.user.login }: <{ pull_request.html_url }|{ pull_request.title }>
